### ISSUE TITLE
Fix OGP.me meta tags

### ISSUE THREAD

**Issue by JeffreyHyer** [JeffreyHyer/nookandcrannydigest#9]
Fix the meta tags describing the individual posts so they appear better on Twitter/FB/etc.

- [ ] Use the post title as the main header line when shared
- [ ] Add a description of the articles contents that shows up as a subheader when shared
- [ ] Add an image that can be used when sharing to social media (single one for the site? article specific image?)
